name: inventory_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.1

workspace:
  - packages/**

dependencies:
  app_ui:
    path: packages/app_ui
  authentication_service:
    path: packages/authentication_service
  bloc: ^9.2.0
  bloc_concurrency: ^0.3.0
  bloc_test: ^10.0.0
  collection: ^1.19.1
  firebase_authentication_service:
    path: packages/firebase_authentication_service
  firebase_core: ^4.4.0
  firebase_part_remote:
    path: packages/firebase_part_remote
  firebase_stock_remote:
    path: packages/firebase_stock_remote
  firebase_storage_remote:
    path: packages/firebase_storage_remote
  firebase_tag_remote:
    path: packages/firebase_tag_remote
  firebase_user_remote:
    path: packages/firebase_user_remote
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  part_remote:
    path: packages/part_remote
  part_repository:
    path: packages/part_repository
  rxdart: ^0.28.0
  stock_remote:
    path: packages/stock_remote
  stock_repository:
    path: packages/stock_repository
  storage_repository:
    path: packages/storage_repository
  tag_remote:
    path: packages/tag_remote
  tag_repository:
    path: packages/tag_repository
  user_remote:
    path: packages/user_remote
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_lint: ">=0.3.3 <0.3.6"
  bloc_tools: ^0.1.0-dev.20
  build_runner: ^2.11.1
  flutter_test:
    sdk: flutter
  melos: ^7.4.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter:
  generate: true
  uses-material-design: true

melos:
  scripts:
    boot:
      description: "Bootstrap the repo via FVM"
      run: fvm dart run melos bootstrap
    gen:
      description: "Run build_runner in the app (lib)"
      run: fvm dart run build_runner build --delete-conflicting-outputs
    gen-packages:
      description: "Run build_runner in all packages"
      run: melos exec --depends-on=build_runner -c 1 -- fvm dart run build_runner build --delete-conflicting-outputs
    l10n:
      description: "Generate Flutter localization"
      run: fvm flutter gen-l10n
    test:flutter:
      run: melos exec --flutter --dir-exists=test -- flutter test
    test:dart:
      run: melos exec --no-flutter --dir-exists=test -- dart test
    test:
      run: melos run test:dart && melos run test:flutter
