name: firebase_tag_remote
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  firebase_shared:
    path: ../firebase_shared
  cloud_firestore: ^6.1.2
  tag_remote:
    path: ../tag_remote

dev_dependencies:
  fake_cloud_firestore: ^4.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.29.0
  very_good_analysis: ^10.2.0

resolution: workspace
