name: ci

on:
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
      - "test/**"
      - "packages/**"
      - "pubspec.yaml"
      - ".github/workflows/main.yaml"

jobs:
  flutter_ci:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "**/*.g.dart **/*.freezed.dart **/*.gen.dart **/l10n/*.dart **/l10n/**/*.dart **/bootstrap.dart"
      coverage-min: 80
